# Generated by Django 5.0.10 on 2025-02-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='feature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
