# Generated by Django 5.0.10 on 2025-02-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionprice_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='feature',
        ),
        migrations.AddField(
            model_name='subscription',
            name='feature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
