# Generated by Django 5.0.10 on 2025-01-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_usersubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='subscriptions',
            new_name='subscription',
        ),
    ]
